# -*- coding: utf-8 -*-
"""Sumarização por frequência.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ED1IztM2ZlFETxLYBdGM-MH1b-nSXe6G

Pré-processamento
"""

import re
import nltk
import string

original = """"- A barra de rolamento é muito fina, dificulta o manuseio e agilidade no uso do sistema

- Sistema lento

- Dificuldade de acesso a fichas de cadastro individual, mesmo com os dados corretos"
10
A agilidade do sistema e espaço pra relata as visitas domiciliares que esse programa não tem.
"a atualização de sistema continuo , atrapalhar demais.
poderia simplifica mais, e tira muitos bug que aparecem no dia a dia."
a conexão do site é muito instável
A instabilidade constante e o fato do programa não ser on line.
a outra versão era mais fácil, muito dificil achar o que procuramos nele na tela inicial
A PESQUISA DE PACIENTE PARA ADICIONAR FICOU MUITO DIFÍCIL ANTES COM O CPF O PACIENTE ERA ENCONTRADO NO CARTÃO SUS AGORA VOCÊ COLOCA O CPF E PEDE PARA CADASTRAR O PACIENTE QUANDO VOCÊ CONCLUI DA ERRO DIZENDO QUE O CNS JÁ ESTÁ CADASTRADO.
"A tela de visualização ficou muito cheia DE INFORMAÇÕES, sugestão sobre a reclassificação de risco do paciente, que poderia haver uma maneira de reclassificar. 
O pec quando sai fora de ar,  e está no nome de um funcionário , não é possível  finalizar ou decorrer o atendimento a não ser o próprio atendente."
A versão anterior muito melhor para,manejar.
A VERSÃO EM SI ELA É MAIS MODERNA E BOA DE SE TRABALHAR NO QUESITO LEIAUT, PORÉM NOTO MAIS INSTABILIDADE DA REDE.
Acho a versão muito vaga. não inclui campo de informação onde o profissional possa descrever o que fez no atendimento ou na visita. seria interessante criar algo parecido, onde pudessemos informar os procedimentos feitos  durante o tal atendimento ou visita, de um modo descritivo. dessa forma a comunicação se tornaria muito viavel, e poderia ser usado em rede.  sugestivo.
Acredito que este sistema teria que ser mais prático, fácil acesso a qualquer leigo
agilidade
agilidade no retorno das informações.
Antes era mais fácil para adc o paciente no sistema, hoje é mais complicado.
Ao acessar a janela de dados cadastrais, para retornar ao SOAP não há como retornar no cabeçalho, somente no final da pagina em voltar. Uma questão que ajudou bastante foi que aparece a idade do paciente já na lista de atendimento.
Atrasa muito nas atualizações do sistema.  As inconsistencias demora muito para serem atualizadas.
atualizaçao
"burocratico demais, muitos cliques.
Lista de atendimentos geral e não individul.
Medicamentos sem lista personalizada e de dificil impressao. 
Prontuario medico extenso demais com tudos os atendimentos juntos, não separa por especialidade ou por atendimentos do mesmo proficional, dificultando a continuidade dos assuntos. Enfim existem muitas situaçoes a aserem mudadas. abs"
cai o sistema diariamente ou desloga do meu login e perco toda a evolução
cai toda hora o sistema
Comparando com a versão anterior, que na minha opinião estava boa, essa nova versão piorou o modo de ver, bem mais confusa, forçando ao erro.
confusa a visualização e perdesse muito tempo no atendimento na inclusão de cadastro.
corrigir os erros e alterar as informações que aparecem durante a colocação de pessoas no sistema.
Deveria haver mais agillidade para colocar resultados de exames. Ao invés de ter que clicar na seta para abrir uma janela e digitar a observação, já deveria existir uma caixa de observação que pudesse ser selecionada e digitada facilmente na própria interface do SOAP.
DIFICULDADE EM VISUALIZAR O PRONTUARIO.SEGUIMENTO DAS CONSULTAS.RECEITAS DIFICIL CONFECÇÃO.
Em alguns momentos apos adicionar o paciente, ele some! dai temos que ficar mexendo no filtro. Dai depois de insistir algumas vezes ele reaparece!
Em relação cadastro colocar a folhas de cadastro individual junto com domiciliar.
Era mais pratico na versão anterior
Esquema trava bastante.
essa nova versão apresenta muita instabilidade, as demais estavam ok
Está tendo muita instabilidade. Deveriam consultar quem usa p sugestões de melhoria.
Exportação da produção nem sempre funciona, não dá para visualizar a razão do porque não foi exportado.
facilidade de identificar  avaliação ,esta muito misturado agendamento com outrs atendimentos
falta a lista de pacientes atendidos que desaparece após o atendimento e possibilidades de retoamr o atendimento, fazer adendos e correções
Faltam muitos diagnósticos no CIAP...por exemplo, atraso do desenvolvimento motor
Ficou mais difícil de atualizar endereço de cadastros ao inserir o paciente para atendimento. Ter o endereço atualizado é importante para quando o médico faz as receitas e quando precisamos manter contato com os pacientes
funcionalidade
Funcionalidade e desempenho.
Gostaria de acessar os itens com mais facilidade. Não consigo acessar o histórico vacinal do paciente.
inconsistência, e falta de campos para adicionar o paciente,  uma agenda mais inteligente  que possamos agendar o paciente de acordo com a classificação de risco que utilizamos aqui em londrina-pr
"Inoperante com frequência;
Quando encaminhamos o paciente para outro profissional no mesmo dia não aparece na minha produção; 
Falta relatório de faltosos na vacina (principalmente em menores de 4 anos); 
No atendimento de consulta não é possível sinalizar o paciente para medicação com classificação de prioridade;
Quando é incluído a gestante no sistema mesmo que o CIAP esteja correto,  quando é solicitado relatório não aparece como pré natal."
Integração com outros bancos de informação em saúde nacionais
interface mais intuitiva e visual mais fluido e dinamico
lenta
mais atualizaçoes
mais diagnósticos
melhora as formas de ver inconcistencia e informa o erro
Melhorar o layout
Melhorar o tempo de refresh da pagina, diminuir o lentidão do sistema e correção dos erros de salvamento automático.
mesmo selecionando os filtros dificulta a equipe localizar os pacientes muitas vezes .A cor verde ajudava muito a facilitar o layout e ver quem estava triado
"Mudou layout porém teve poucas mudanças que agilizam o uso cotidiano e facilitam o acompanhamento da população, por exemplo,os relatórios ainda não condizem com a realidade da população. 
Também é necessário facilitar as ações como, acesso ao prontuário por profissionais de nível superior, incluir possibilidade de fechar agenda em ampla escala e ect..."
Muita informação na tela .
MUITAS FALHAS NOS CADASTROS DE GESTANTES, HIPERTENSOS E DIABETICOS
muito difícil
muito poluido
muitos campos para preenchimnto, poucos ciap
muitos dos cadastro já realizados sumirão
Muitos procedimento odontológicos não tem como serem inseridos.
não conseguimos interligar o sistema com o cartão nacional do SUS e unificar os prontuários.
Não consigo mais entrar no cadastro do paciente com essa versão
NÃO CONSIGO OLHAR O CARTÃO SUS DOS PACIENTES AINDA NÃO CADASTRADOS NO SISTEMA . E ISSO DIFICULTA MUITO O TRABALHO DO ACS, POIS TEM PACIENTES QUE DEMORAM MUITO PARA IREM RENOVAR OS CARTÕES DO SUS E ANTES CONSEGUIA PEGAR O NÚMERO DO CARTÃO NOVO NA ABA CIDADÃO E COM ESSA NOVA VERSÃO NÃO ESTOU CONSEGUINDO E NEM O GESTOR LOCAL DA TI CONSEGUI RESOLVER ESSE PROBLEMA.
Não ficar caindo o sistema todo o tempo e apagando tudo o que escrevi
nao temos acesso ao cadweb dificultando assim o acesso as informacoes
não ter acesso a recepção dificulta o meu trabalho
nao ter espaço para relatar dados da vd
nos temos de atualizar cadastro novamente com cpf, e o sistema nao unifica, deveria no momento de entrar com CPF  ja buscar todas as informaçoes sobre o cliente
"O ""autosave"" poderia ser mais rapido, pq ainda perdemos dados. Tb acontece qdo escrevemos a conduta em PLANO e depois clicamos p/ realizar receita ou encaminhamento... perde tudo...
- Poderia poder personalizar quais exames pedimos mais.
- A consulta inicial meio que perde utilidade, pois devido a ela ser mais enxuta, os aux. de enf. acabam usando o SOAP. Mas soap nao tem classificação de risco... SE desse p/ unificar eles... e no fim do atendimento, o profiss. escolhe se é soap ou escuta inicia"
o e sus não puxa suas familia por si propia , quando e feito o cadastro e ja coloca o responsavel.
o historico do médico deveria ser algo unico, ruim ter que abrir tela por tela pra entender toda a evolução do paciente, demora muito
O mais importante é a simplicidade, no momento mudaram a versão não deram suporte de ensino pra o novo sistema, deixando confuso o funcionamento e como utilizar
"O PEC continua muito lento e pouco fluido entre as transições de telas. Percebi um problema também que quando fazermos a prescrição dos medicamentos para imprimir o PEC apaga o que já estiver escrito no PLANO o que faz que precise ser preenchido novamente. 
Seria bom também que ao colocarmos as aferições das medidas de gestantes e crianças aparecessem montadas nos gráficos para sabermos como está a situação da paciente em relação à curva normal."
o programa numca abre
O sistema ainda trava muito.
"O sistema é lento, instável e tem bugs. 
Não conseguimos colocar o estado de nascimento, muitas vezes e buga e não passa da letra A, temos que realizar várias tentativas pra colocar, visto que a tela não muda se não for colocado."
o sistema e mais complicado que a versao anterior
O sistema esta muito pesado e trava muito, as vezes nao carrega informações precisas.
o sistema ficou com muitos campos para precher. poderia reduzir. como queixa principal, anamnese e conduta
"o sistema não salva  automático.  No meio de uma consulta ele atualiza e perdemos tudo.  Outro  ponto importante é o sistema poder acessar diretamente os exames .
Acrescentar outras classificações no CID, específicas a nutrição, como por exemplo: 
GASTROSTOMIA
SONDA NASOGÁSTRICA OU NASOENTERICA
ERRO ALIMENTAR
DESNUTRIÇÃO PROTEICO CALÓRICO"
o sistema sai do ar, acaba travando e perde tudo que vc escreveu!!!
pacientes que nao estao cadastrados, colocar na lista de atendimentos apenas com o cns.
Pec fica muito tempo fora do ar e isto é ruim, pois os pacientes ficam muito tempo aguardando, sendo que todas as agendas estão no PEC. Para visualizar prontuário é complicado.
Poder dar o diagnóstico correto e poder registra-lo assim. Tem muitas doenças que são mais usadas na fisioterapia e não estão nas opções disponíveis.
Poder personalizar as listas de exames nos atendimentos
Poder reavaliar o paciente sem mudar o horário na lista de espera e conseguir realizar troca a classificação de classificação de risco quando necessário. Ex= De verde para amarelo
Pouco dinâmico para inserir exames e medicamentos.
praticidade
Praticidade,agilidade.
Precisa de mais ciap-2 cadastrado, especifico para os programas da saúde da família.
precisa melhorar na questão de iniciar o programa, demora muito para entrar.
Precisar melhorar muitonouseJa deixar só um para que possamos trabalhar melhor com a consolidação dos dados.
Que o sistema funcione, cedo começa o atendimento e o sistema fora doar. e que fossem adaptados para atendimento a odontopediatria.
rapidez e eficiência, o que não dá para ter, já que a cada minuto o sistema fica perguntando se eu quero sair
Sistema com muita instabilidade, fazendo perder anotações e produções do dia
SISTEMA DEIXA MUITO A DESEJAR, NÃO GERA RELATORIOS ESPECIFICOS, POIS É MUITO RESUMIDO, NÃO DETALHA POR NOME DE VACINADOS E VACINAS ESPECIFICAS. A CAEDENETA DE VACINA NÃO SEGUE A ATUALIZAÇÃO, EXEMPLO: A GESTANTE TOMA 2 DOSES DE DUPLA ADULTO E QUANDO VEM PARA TOMAR A TERCEIRA DOSE NÃO TEM A OPÇÃO DE DTPa COMO TERCEIRA DOSE. ENFIM SISTEMA SEM DETALHES PARA FACILITAR NOSSO TRABALHO.
Sistema funcionando
Sistema inconsistente sempre. Nem sempre salva o prontuário
Sistema muito instável, fica tão lento que muitas das vezes não é possível concluir o atendimento do paciente no mesmo dia. Isso nos obriga a fazermos registro de atendimento tardio, tomando o tempo de trabalho do dia seguinte.
sistema nao esta atualizado e trava muito
Sistema quase sempre fora do ar
"SISTEMA TRAVA MUITO.
NÃO TEM ACESSO AO HISTÓRICO AO ACESSAR A ESCUTA INICIAL, TEM QUE FICAR MUDANDO DE TELA."
"Sugestão:
em AGENDA: 
opção de selecionar mais de um horário para reserva.
CONFIGURAÇÃO DA AGENDA
opção para nomear agendar no cabeçalho separando por clínica exemplo criança, gestante, adulto."
trava demais, sistema muito pesado
trava muito
TRAVA MUITO ATRAPALHANDO OS ATENDIMENTOS
Trava muito, e CPF e CNS não se conversam em alguns casos.
treminamento sobre o sistema mais intenso e ou rotineiro d 3 ou 6/6 messes para nao ter margens de erro e perda de produçao e dados importantes para alimentaçao do sistema. aumentar as lista de notificaçoes de agravos, dificuldades para agrovos de outros tipos de patologias
Vinculação do paciente,perdemos muito tempo."""

original

original = re.sub(r'\s+', ' ', original)

original

nltk.download('punkt')

nltk.download('stopwords')

stopwords = nltk.corpus.stopwords.words('portuguese')
print(stopwords)

string.punctuation

def lower(input):
  lowered = input.lower()
  tokens = []
  for token in nltk.word_tokenize(lowered):
    tokens.append(token)

  tokens = [palavra for palavra in tokens if palavra not in stopwords and palavra not in string.punctuation]

  formatado = ' '.join([str(elemento) for elemento in tokens])

  return formatado

formatado = lower(original)
formatado

"""**Frequência palavras**"""

frequencia = nltk.FreqDist(nltk.word_tokenize(formatado))
frequencia

"""**Frequência proporcional das palavras**"""

max_freq = max(frequencia.values())
max_freq

for palavra in frequencia.keys():
  frequencia[palavra] = frequencia[palavra] / max_freq

frequencia

"""**Tokenização**"""

sentencas = nltk.sent_tokenize(original)
sentencas

"""**Nota sentenças**"""

notas = {}
for sentenca in sentencas:
  for palavra in nltk.word_tokenize(sentenca.lower()):
    if palavra in frequencia.keys():
      if sentenca not in notas.keys():
        notas[sentenca] = frequencia[palavra]
      else:
        notas[sentenca] += frequencia[palavra]

notas

"""**Ordenação das sentenças**"""

import heapq
melhores = heapq.nlargest(10, notas, key=notas.get)

resumo = ' '.join(melhores)
resumo

original

from IPython.core.display import HTML
texto = ''

display(HTML(f'<h1>4.1.14 - Insatisfeitos</h1>'))
for sentenca in sentencas:
  if sentenca in melhores:
    texto += str(sentenca).replace(sentenca, f"<mark>{sentenca} </mark>")
  else:
    texto += sentenca + ' '
display(HTML(f"{texto}"))

!pip install goose3

from goose3 import Goose

g = Goose()
url = 'https://iaexpert.academy/2020/11/09/ia-preve-resultado-das-eleicoes-americanas/'
artigo = g.extract(url)

artigo.infos

original = artigo.cleaned_text