# -*- coding: utf-8 -*-
"""Sumy, Pysummarization, BERT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Nt3OYRdljJbCqf1_9fQ4O1a0OXaCzy_R

# Sumy
"""

import nltk
nltk.download('punkt')

!pip install goose3

from goose3 import Goose
g = Goose()
url = 'https://iaexpert.academy/2020/11/09/ia-preve-resultado-das-eleicoes-americanas/'
pt = g.extract(url)

url = 'https://en.wikipedia.org/wiki/Artificial_intelligence'
en = g.extract(url)

pt.cleaned_text
en.cleaned_text

!pip install sumy

from sumy.parsers.plaintext import PlaintextParser
from sumy.nlp.tokenizers import Tokenizer
from sumy.summarizers.luhn import LuhnSummarizer
from sumy.summarizers.lsa import LsaSummarizer
from sumy.summarizers.lex_rank import LexRankSummarizer
from sumy.summarizers.text_rank import TextRankSummarizer
from sumy.summarizers.sum_basic import SumBasicSummarizer
from sumy.summarizers.kl import KLSummarizer
from sumy.summarizers.reduction import ReductionSummarizer

parser = PlaintextParser.from_string(pt.cleaned_text, Tokenizer('portuguese'))

sumLuhn = LuhnSummarizer()
sumLSA = LsaSummarizer()
sumLEX = LexRankSummarizer()
sumRank = TextRankSummarizer()
sumBasic = SumBasicSummarizer()
sumKL = KLSummarizer()
sumRed = ReductionSummarizer()

resumoLuhn = sumLuhn(parser.document, 5)

resumoLSA = sumLSA(parser.document, 5)

resumoLEX = LexRankSummarizer(parser.document, 5)

resumoRank = TextRankSummarizer(parser.document, 5)

resumoBasic = SumBasicSummarizer(parser.document, 5)

resumoKL = KLSummarizer(parser.document, 5)

resumoRed = ReductionSummarizer(parser.document, 5)

resumo

for sentenca in resumo:
  print(sentenca)

"""# Pysummarization"""

!pip install pysummarization

from pysummarization.nlpbase.auto_abstractor import AutoAbstractor
from pysummarization.tokenizabledoc.simple_tokenizer import SimpleTokenizer
from pysummarization.abstractabledoc.top_n_rank_abstractor import TopNRankAbstractor

abstractor = AutoAbstractor()
abstractor.tokenizable_doc = SimpleTokenizer()
abstractor.delimiter_list = ['.', '\n']
abstractable = TopNRankAbstractor()

resumo = abstractor.summarize(en.cleaned_text, abstractable)

resumo

for sentenca in resumo['summarize_result']:
  print(sentenca)

"""# BERT

"""

!pip install bert-extractive-summarizer

!pip install bert-tensorflow

!pip install sentencepiece

from summarizer import Summarizer

sum = Summarizer()
resumo = sumarizador(en.cleaned_text)